### ISSUE TITLE
`init-shell` doesn't properly set variables like CONDA_PREFIX

### ISSUE THREAD

**Issue by aldanor** [mamba-org/setup-micromamba#146]
Build tools like [`maturin`](https://github.com/PyO3/maturin) may [rely](
https://github.com/PyO3/maturin/blob/afb1f037b6dca65955a017b9ee4110eaf44acd1a/guide/src/environment-variables.md?plain=1#L9-L12) on `CONDA_PREFIX` (or `VIRTUAL_ENV`) environment variables to determine the current Python environment to build bindings for.

With the old provision-micromamba you would do `micromamba activate foo && maturin build`, but now it wouldn't detect the correct Python interpreter.

Should those environment variables be set in `init-shell`?

**Comment by pavelzw** [comment]
These environment variables come from `micromamba activate foo`. This should also be available in `setup-micromamba`. Do you have a failing example?
