### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by karkir0003** [mamba-org/setup-micromamba#148]
is the `setup-micromamba` action compatible with using Github's Cache V3 action? If so, can someone provide example .yml file

https://github.com/actions/cache

@mfisher87 , @pavelzw

**Comment by pavelzw** [comment]
It uses the caching API from the @actions/cache JavaScript library.
For examples on how to use caching with setup-micromamba: https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#caching

**Comment by jonashaag** [comment]
@karkir0003 please do a minimum of research yourself and report your findings before opening an issue.

**Comment by pavelzw** [comment]
If you don't use the integrated caching mechanisms, you can use the `actions/cache` action in any way you like.

**Comment by karkir0003** [comment]
Thanks @pavelzw. I was able to unblock myself!
