### ISSUE TITLE
Environment File Name Specification Error

### ISSUE THREAD

**Issue by karkir0003** [mamba-org/setup-micromamba#149]
I don't understand this error message when passing the `environment-file` parameter into the `setup-micromamba` action. Can you help clarify?

```
Error: Could not determine environment name from file /training/environment.yml
Error: Error: Error: ENOENT: no such file or directory, open '/training/environment.yml'
Error: If your environment file is not YAML containing `name` at the top level, please specify the environment name directly.
```

**Comment by karkir0003** [comment]
https://github.com/DSGT-DLP/Deep-Learning-Playground/actions/runs/6230333932/job/16910193521

**Comment by pavelzw** [comment]
no such file or directory, open '/training/environment.yml'

it cannot file the file `/training/environment.yml`.

this has two reasons:
- file path was incorrectly specified: should be `training/environment.yml`
- The repository was not cloned yet so the environment file doesn’t exist yet

the error message could be a bit more clear

**Comment by jonashaag** [comment]
@karkir0003 again, please do at least some effort to understand the problem and provide a list of things that you have tried that haven't worked out before opening an issue.

**Comment by karkir0003** [comment]
> > no such file or directory, open '/training/environment.yml'
> 
> it cannot file the file `/training/environment.yml`.
> 
> this has two reasons:
> 
> * file path was incorrectly specified: should be `training/environment.yml`
> * The repository was not cloned yet so the environment file doesn’t exist yet
> 
> the error message could be a bit more clear

Got it resolved. Turns out that I needed to run the checkout action before the `setup-micromamba` action. Thanks team!
