### ISSUE TITLE
Improve Shell Default Arguments

### ISSUE THREAD

**Issue by mikemhenry** [mamba-org/setup-micromamba#151]
RE: https://github.com/mamba-org/setup-micromamba#about-login-shells

I am wondering if we should advise people to use something like `shell: bash -leo pipefail {0}` instead of `shell: bash -l {0}` since the default-ish behavior here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell is for shells to set `-e`, which users will lose if only `-l` is used. 

I am happy to submit a PR for this document tweak.

**Comment by pavelzw** [comment]
Sounds good, happy to merge 👍🏻
