### ISSUE TITLE
Segfault - Not sure how to root cause

### ISSUE THREAD

**Issue by karkir0003** [mamba-org/setup-micromamba#155]
I'm trying to run a github action to install poetry dependencies and cache the venv within mamba. Here is a [link](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/.github/workflows/backend.yml) to the github actions yml file and a [link](https://github.com/DSGT-DLP/Deep-Learning-Playground/actions/runs/6371725006/job/17293916310?pr=965) to the failed run. Could someone take a look and provide me with pointers on how to debug the cause of the segfault? I'm wondering if micromamba might be the cause of the segfault?

**Comment by jonashaag** [comment]
Looks like a segfault in poetry. You could try running it in gdb/lldb and dumping the stack.

**Comment by karkir0003** [comment]
Can you show how I can set that up in github action?

**Comment by pavelzw** [comment]
Try using https://github.com/mxschmitt/action-tmate
This opens an ssh shell which you can access.

**Comment by karkir0003** [comment]
@pavelzw Was able to temporarily resolve this by switching to another github action [here](https://github.com/conda-incubator/setup-miniconda)
