### ISSUE TITLE
hanging

### ISSUE THREAD

**Issue by jmccreight** [mamba-org/setup-micromamba#216]
mamba-org/setup-micromamba@v1 just hangs. If I add `log-level: debug` it seems to solve the problem.

Before:
https://github.com/EC-USGS/pywatershed/actions/runs/9702052355/job/26777011872

After:
https://github.com/EC-USGS/pywatershed/actions/runs/9702122897/job/26777262099

I've seen it happen on multiple platforms but OSX seems to be the most consistently problematic. I've cleared my cache and that didnt help.

**Comment by pavelzw** [comment]
i'm wondering whether this is an issue with setup-micromamba or with micromamba 🤔

**Comment by jmccreight** [comment]
Good point. I dont have the problem at all locally, so I assumed it was something with the runner or the action.
I also submitted this issue a bit early, the second link is still working. Hopefully it will show what i've found before after a few more minutes

**Comment by jmccreight** [comment]
Ironically, the jobs now appear to hang regardless. It seemed odd that the logging would break the log jam, but it seemed to work since last week until now. I'll reopen this if I have any better reasons to suspect it's the action.
