### ISSUE TITLE
$MAMBA_EXE not in $PATH on macos-latest runners

### ISSUE THREAD

**Issue by mattwthompson** [mamba-org/setup-micromamba#224]
On macOS, the executable is installed into `/Users/runner/micromamba-bin/micromamba`, which is not in `$PATH` on `macos-latest` (M1 runners) but is on `macos-12` (Intel architecture). This appears to be the root cause of surprising behavior i.e. commands like `which micromamba` fail. Here is a reproducing workflow: https://github.com/mattwthompson/micromamba-path-reproduction/actions/runs/10891923866/workflow

Credit to @ethanholz for trying a bunch of things that resulted in narrowing this down.

We can work around this by setting `micromamba-binary-path` but this doesn't seem like it should be required. In fact, I didn't have to set this option in the past. This [behavior changed](https://github.com/openforcefield/status/actions/workflows/full-stack.yaml?query=event%3Aschedule) sometime around Friday of last week (9/13 or 9/14) for reasons I'm unable to pin down:
* Runner image changes seem minimal to me: https://github.com/actions/runner-images/pull/10603/files
* No recent releases of this action (this commit from May is referenced: https://github.com/mamba-org/setup-micromamba/commit/f8b8a1e23a26f60a44c853292711bacfd3eac822)
* No recent releases of `mamba` itself (1.5.9 is used)

Am I doing something wrong here? Was I doing something wrong before?

**Comment by pavelzw** [comment]
xref https://github.com/actions/runner-images/issues/10624, https://github.com/prefix-dev/setup-pixi/issues/139

**Comment by mattwthompson** [comment]
Ah thanks! I figured it was probably a more widespread issue and was surprised it hadn't been reported here earlier today. Quite messy

**Comment by pavelzw** [comment]
Seems to be fixed upstream.
