### ISSUE TITLE
Release missing for v2

### ISSUE THREAD

**Issue by maresb** [mamba-org/setup-micromamba#235]
Renovate-bot is [going to town](https://github.com/conda/conda-lock/pull/719) with the v2 of setup-micromamba. I wanted to check the release notes, but saw that there had not yet been a release.

Thanks so much for all your hard work in fixing the recent problems!

**Comment by maresb** [comment]
The current diff between the v1 and v2 series is:
https://github.com/mamba-org/setup-micromamba/pull/234

In case anyone else is hunting for info before a real response comes, my very vague understanding is that there was some conflict with a preexisting `micromamba.bat` script on the Windows runner, and this PR clobbers the bad thing, making it work.

**Comment by maresb** [comment]
This release seems to have solved mamba-org/mamba#3467 for me on GHA.

**Comment by pavelzw** [comment]
https://github.com/mamba-org/setup-micromamba/releases/tag/v2.0.0
