### ISSUE TITLE
cmd.exe shell doesn't work with micromamba 1

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/setup-micromamba#237]
#234 broke old micromamba versions, see #236

![image](https://github.com/user-attachments/assets/5815b442-b960-4d35-9c46-a03e73bbb011)

**Comment by pavelzw** [comment]
CC @JohanMabille @jjerphan

**Comment by pavelzw** [comment]
Also, could you introduce a comment in the code relevant code line referencing to https://github.com/mamba-org/setup-micromamba/issues/230#issuecomment-2391367425 ?

Otherwise nobody will know why this change was made in a year from now

**Comment by pavelzw** [comment]
if you decide that you don't want to support micromamba 1 for setup-micromamba@v2, we should at least print out a meaningful error message that indicates this

**Comment by jjerphan** [comment]
I think that both major versions of `micromamba` and `setup-micromamba` must be tied, and that this should be documented.

**Comment by maresb** [comment]
I'm seeing this now with v2 [here](https://github.com/pymc-devs/pymc/actions/runs/12014314467/job/33489846282?pr=7585#step:3:22)

**Comment by jjerphan** [comment]
This should be fixed by https://github.com/mamba-org/setup-micromamba/pull/246.

**Comment by jjerphan** [comment]
Can an admit [review and publish 2.0.2 on GitHub Marketplace](https://github.com/mamba-org/setup-micromamba/releases/tag/untagged-24463f3be6ac9c960c38)? For instance, @pavelzw? :pray:
