### ISSUE TITLE
Critical libmamba error related to character encoding

### ISSUE THREAD

**Issue by Zeitsperre** [mamba-org/setup-micromamba#243]
Hi there, I noticed today that setup-micromamba's libmamba seems to be failing for me in my Windows builds: https://github.com/Ouranosinc/raven-hydro/actions/runs/11693031236/job/32604561549

It seems as though this is an encoding error (for the :sparkles: emoji?): 
```
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 8: character maps to <undefined>
```

I'm not able to see what has changed, as it seems to fail at the `list` step, but most of my dependencies are pinned. I know that `black` uses the :sparkles: emoji and has done so for years, so I'm not sure where the issue is.

**Comment by dopplershift** [comment]
Looks like based on https://github.com/mamba-org/mamba/issues/3576 a work-around is to roll back to 2.0.2-2.

**Comment by JohanMabille** [comment]
This has been fixd in 2.0.4.

**Comment by maxnoe** [comment]
I just ran into the same or at least very similar issue in this CI run: https://github.com/cta-observatory/ctapipe/actions/runs/17240861470/job/48917449502?pr=2156

> critical libmamba No mapping for the Unicode character exists in the target multi-byte code page.
  Error: The process 'C:\Users\runneradmin\micromamba-bin\micromamba.exe' failed with exit code 1
