### ISSUE TITLE
Can not run sphinx-build or access any sphinx plugins

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [mamba-org/setup-micromamba#250]
recently I have changed my github actions work flow to use conda packages instead of package installed via pip to more closely align with my development environment for my project's github action workflow. For some reason I sphinx is unable to run sphinx-build commands or find sphinx extensions that were installed via conda.

[link to my project's github action workflow](https://github.com/USEPA/pyaqsapi/blob/github_workflow/.github/workflows/newbuildandtestpyaqsapi.yml)

[link to the environment.yml file which list the dependencies that were installed prior to running the command](https://github.com/USEPA/pyaqsapi/blob/github_workflow/environment.yml)

One solution possible to this is to run the conda init command or append the file location /opt/conda to the $PYTHONPATH environment variable. I have tried both and neither solution seems to work while using github actions. My understanding is that setup-micromamba should do this for the user anyways.

Can some one please advise me as to how to get sphinx working using conda packages in a github actions/runner environment?

**Comment by pavelzw** [comment]
You need to specify your shell in following commands, see https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#about-login-shells

**Comment by pavelzw** [comment]
if you add this to the top of your github workflow, it should work

```yml
defaults:
  run:
    shell: bash -el {0}
```

you can also get rid of `actions/setup-python@v4` as micromamba environments come with a separate python version

**Comment by mccroweyclinton-EPA** [comment]
Thank you

**Comment by mccroweyclinton-EPA** [comment]
Thank you
