### ISSUE TITLE
Environment creation fails if environment.yml file has comments at top of file

### ISSUE THREAD

**Issue by GBBBAS** [mamba-org/setup-micromamba#81]
Hi,

Recently, this github action started failing for my pipeline where it used to work before with the following error:
`Error: Could not determine environment name from file environment.yml`

Example:
https://github.com/rtdip/core/actions/runs/5241275225/jobs/9463153612

I have identified that this occurs when there are comments at the top of the file. When I remove the comments, the environment install works.

Did something change in this github action that causes this to now happen? Ultimately we need to have copyright headers at the top of the file, so would like this to work.

**Comment by pavelzw** [comment]
Hmm, this may have something to do with #79 which I released three days ago. I'll look into it.

**Comment by pavelzw** [comment]
Thanks for the quick issue! I fixed it in #82 and added a unit test covering [your case](https://github.com/mamba-org/setup-micromamba/blob/b6f8616e8db64a26288ad65dc847456b7f6dbac5/.github/workflows/test.yml#L176).

**Comment by GBBBAS** [comment]
Awesome, thanks for the quick response!
