### ISSUE TITLE
Add micromamba version to cache key?

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/setup-micromamba#91]
If you change the Micromamba version (implicit update due to new release, explicit update to due version pin) any environment cached with a previous Micromamba version is restored.

I wonder if we should make the cache dependent on the Micromamba version because there might be bug fixes in newer versions that affect the environment

**Comment by pavelzw** [comment]
Yes, that sounds reasonable 👍

**Comment by bhperry** [comment]
Speaking of.... [this issue](https://github.com/mamba-org/setup-micromamba/issues/225) became a whole lot more painful to deal with because of this

**Comment by pavelzw** [comment]
it would probably be easiest to just include the sha256 of the micromamba executable in the cache key. PRs are welcome :)
